#!/usr/bin/env sh
set -ex
mkdir -p out
time ./go --peg-preprocessor include/include > out/include
time ./go --peg-preprocessor include/shared > out/shared
time ./go --peg-preprocessor include/um > out/um
echo Success
