#!/usr/bin/env sh
set -ex
mkdir -p out
./go --peg-preprocessor include > out/include
./go --peg-preprocessor 10.0.17763.0/shared > out/shared
./go --peg-preprocessor 10.0.17763.0/um > out/um
echo Success
